In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('vendas.xlsx')

In [ ]:
# Exemplo python funções string puro
texto = '  tEXto BLA  '
type(texto)
texto.replace('BLA','')

'  tEXto   '

In [ ]:
df['Resposta'] = df['Resposta'].str.lower().str.strip().str.title()

In [ ]:
df['Descricao'] = df['Descricao'].str.replace('#$%!', '')

In [ ]:
df['Preco_Compra']

In [ ]:
df['Preco_Compra'] = df['Preco_Compra'].str.replace('R$ ','')
df['Preco_Compra'] = df['Preco_Compra'].str.replace('.', '').str.replace(',', '.')
df['Preco_Compra'] = pd.to_numeric(df['Preco_Compra'])

In [ ]:
df['Quantidade'] = df['Quantidade'].astype(str).str.replace('items', '')

In [ ]:
df['Preco_Compra'] = df['Preco_Compra'].fillna(df['Preco_Unitario']*df['Quantidade'].astype(int))

In [ ]:
# Filtro para apresnetar os valores do campo Nome nulos
df[df['Nome'].isnull()]

In [ ]:
df['Nome'] = df['Nome'].fillna('Desconhecido')

In [ ]:
df['Data_Nascimento'] = pd.to_datetime(df['Data_Nascimento'], format='%d/%m/%Y', errors='coerce')

In [ ]:
df['Data_Nascimento'][1]

datetime.datetime(1961, 1, 8, 0, 0)

In [ ]:
### Exercícios #3

In [ ]:
df.groupby('Resposta').agg({'Preco_Compra':['mean', 'count']})

         Preco_Compra
                 mean count
Resposta
Não       3375.849062    32
Sim       2240.451212    33
Talvez    2916.660000    35

In [ ]:
dfv = df[df['Data_Nascimento']>="2004-01-31"]
dfv.groupby('Resposta').agg({'Preco_Compra': ['sum', 'min','max']})

         Preco_Compra
                  sum      min      max
Resposta
Não          14877.71  1096.13  7910.46
Sim            696.50   696.50   696.50
Talvez        5946.30  5946.30  5946.30

In [ ]:
dfv

,index,ID,Nome,Data_Nascimento,Preco_Unitario,Data_Venda,Data_Cadastro,Resposta,Descricao,Quantidade,Preco_Compra
5,5,3,Desconhecido,2004-09-15,345.36,2022-10-13,2023-05-02,Não,Bom produto.,17,5871.12
41,41,10,Beatriz Almeida,2004-05-18,156.59,2022-01-05,2021-10-25,Não,Aprovado 100%.,7,1096.13
43,43,1,Fernanda Pereira,2004-08-21,348.25,2020-08-15,2022-11-21,Sim,Ótimo custo-benefício.,2,696.50
77,77,8,Roberto Costa,2004-08-10,396.42,2024-04-05,2019-06-10,Talvez,Produto Excelente!,15,5946.30
86,86,6,Desconhecido,2005-05-17,439.47,2022-12-25,2023-07-17,Não,Produto de confiança.,18,7910.46

In [ ]:
df['Resposta']